# Generated by Django 5.0.1 on 2024-01-13 09:55

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidades', models.CharField(blank=True, max_length=50, verbose_name='Habilidades')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('card', models.CharField(max_length=40, verbose_name='Tarjeta')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('t_documento', models.CharField(choices=[('DNI', 'DNI'), ('CI', 'CI'), ('PASAPORTE', 'PASAPORTE'), ('CARNET DE EXTRANGERIA', 'CARNET DE EXTRANJERIA')], default='DNI', max_length=30, verbose_name='Tipo de Documento')),
                ('n_documento', models.IntegerField(verbose_name='Numero de documento')),
                ('foto', models.ImageField(upload_to='foto/', verbose_name='Foto')),
                ('n_telefonico', models.IntegerField(verbose_name='Numero de telefono')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('dotacion', ckeditor.fields.RichTextField(blank=True, verbose_name='Dotacion de uniformes')),
                ('aportes', ckeditor.fields.RichTextField(blank=True, verbose_name='Aportes')),
                ('deficiencias', ckeditor.fields.RichTextField(blank=True, verbose_name='Deficiencias')),
                ('recomendaciones', ckeditor.fields.RichTextField(blank=True, verbose_name='Recomendaciones')),
                ('n_faltas', models.IntegerField(blank=True, default=0, verbose_name='Numero de Faltas')),
                ('falta_des', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripcion de faltas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('curriculum', models.FileField(upload_to='curriculums/', verbose_name='Curriculum')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
                ('habilidades', models.ManyToManyField(to='personal.habilidades')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
