# Generated by Django 4.2.1 on 2023-06-08 13:27

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_personal_cargo_alter_personal_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='card',
            field=models.CharField(default=' ', max_length=40, verbose_name='Tarjeta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='personal',
            name='dotacion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Dotacion de uniformes'),
        ),
        migrations.AddField(
            model_name='personal',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
