# Generated by Django 4.2.1 on 2023-06-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LunchEntry',
            new_name='LunchEnd',
        ),
        migrations.RenameModel(
            old_name='LunchExit',
            new_name='LunchStart',
        ),
    ]
