# Generated by Django 4.2.1 on 2023-06-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_personal_card_personal_created_personal_dotacion_and_more'),
        ('employee', '0003_alter_lunchend_options_alter_lunchstart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryhour',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='exithour',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='lunchend',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
        migrations.AlterField(
            model_name='lunchstart',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.personal'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
